<?php

namespace Sufyan\MigrationLinter\Support;

use Illuminate\Support\Str;

class HtmlReporter
{
    /**
     * Generate HTML report from issues.
     *
     * @param  Issue[]  $issues
     * @param  string|null  $outputPath
     * @return string
     */
    public function generate(array $issues, ?string $outputPath = null): string
    {
        $html = $this->buildHtmlDocument($issues);

        if ($outputPath) {
            $directory = dirname($outputPath);
            if (!file_exists($directory)) {
                mkdir($directory, 0755, true);
            }
            file_put_contents($outputPath, $html);
        }

        return $html;
    }

    /**
     * Build complete HTML document.
     */
    protected function buildHtmlDocument(array $issues): string
    {
        $stats = $this->calculateStats($issues);
        $groupedIssues = $this->groupIssuesByRule($issues);
        
        $timestamp = date('Y-m-d H:i:s');
        $projectName = basename(getcwd());

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laravel Migration Linter Report</title>
    <style>
        {$this->getStyles()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🧩 Laravel Migration Linter Report</h1>
            <div class="meta">
                <span class="project">Project: <strong>{$projectName}</strong></span>
                <span class="timestamp">Generated: {$timestamp}</span>
            </div>
        </header>

        {$this->renderSummary($stats)}
        {$this->renderChart($stats)}
        {$this->renderIssuesTable($issues)}
        {$this->renderGroupedSuggestions($groupedIssues)}
        {$this->renderRuleBreakdown($groupedIssues)}

        <footer class="footer">
            <p>Generated by <a href="https://github.com/muhammad-sufyan5/sufyan-laravel-migration-lint-package" target="_blank">Laravel Migration Linter</a></p>
        </footer>
    </div>

    <script>
        {$this->getJavaScript()}
    </script>
</body>
</html>
HTML;
    }

    /**
     * Calculate statistics from issues.
     */
    protected function calculateStats(array $issues): array
    {
        $files = array_unique(array_map(fn($i) => $i->file, $issues));
        
        return [
            'total_issues' => count($issues),
            'total_files' => count($files),
            'errors' => count(array_filter($issues, fn($i) => $i->severity === 'error')),
            'warnings' => count(array_filter($issues, fn($i) => $i->severity === 'warning')),
            'info' => count(array_filter($issues, fn($i) => $i->severity === 'info')),
            'files' => $files,
        ];
    }

    /**
     * Group issues by rule ID.
     */
    protected function groupIssuesByRule(array $issues): array
    {
        $grouped = [];
        foreach ($issues as $issue) {
            $grouped[$issue->ruleId][] = $issue;
        }
        return $grouped;
    }

    /**
     * Render summary section.
     */
    protected function renderSummary(array $stats): string
    {
        $statusClass = $stats['errors'] > 0 ? 'danger' : ($stats['warnings'] > 0 ? 'warning' : 'success');
        $statusIcon = $stats['errors'] > 0 ? '❌' : ($stats['warnings'] > 0 ? '⚠️' : '✅');
        $statusText = $stats['errors'] > 0 ? 'Action Required' : ($stats['warnings'] > 0 ? 'Review Recommended' : 'All Clear');

        return <<<HTML
        <div class="summary status-{$statusClass}">
            <div class="status-badge">
                <span class="status-icon">{$statusIcon}</span>
                <span class="status-text">{$statusText}</span>
            </div>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value">{$stats['total_issues']}</div>
                    <div class="stat-label">Total Issues</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{$stats['total_files']}</div>
                    <div class="stat-label">Files Affected</div>
                </div>
                <div class="stat-card error">
                    <div class="stat-value">{$stats['errors']}</div>
                    <div class="stat-label">Errors</div>
                </div>
                <div class="stat-card warning">
                    <div class="stat-value">{$stats['warnings']}</div>
                    <div class="stat-label">Warnings</div>
                </div>
                <div class="stat-card info">
                    <div class="stat-value">{$stats['info']}</div>
                    <div class="stat-label">Info</div>
                </div>
            </div>
        </div>
HTML;
    }

    /**
     * Render chart section.
     */
    protected function renderChart(array $stats): string
    {
        $total = $stats['total_issues'];
        if ($total === 0) {
            return '';
        }

        $errorPercent = round(($stats['errors'] / $total) * 100);
        $warningPercent = round(($stats['warnings'] / $total) * 100);
        $infoPercent = round(($stats['info'] / $total) * 100);

        return <<<HTML
        <div class="chart-section">
            <h2>📊 Issue Distribution</h2>
            <div class="chart-container">
                <div class="bar-chart">
                    <div class="bar-item error" style="width: {$errorPercent}%">
                        <span class="bar-label">Errors: {$stats['errors']}</span>
                    </div>
                    <div class="bar-item warning" style="width: {$warningPercent}%">
                        <span class="bar-label">Warnings: {$stats['warnings']}</span>
                    </div>
                    <div class="bar-item info" style="width: {$infoPercent}%">
                        <span class="bar-label">Info: {$stats['info']}</span>
                    </div>
                </div>
            </div>
        </div>
HTML;
    }

    /**
     * Render issues table.
     */
    protected function renderIssuesTable(array $issues): string
    {
        if (empty($issues)) {
            return '<div class="no-issues">✅ No issues found. Your migrations look safe!</div>';
        }

        $rows = '';
        foreach ($issues as $index => $issue) {
            $severityClass = $issue->severity;
            $severityBadge = $this->getSeverityBadge($issue->severity);
            $column = htmlspecialchars($issue->snippet ?? '-');
            $message = htmlspecialchars($issue->message);
            $file = htmlspecialchars(basename($issue->file));
            $ruleId = htmlspecialchars($issue->ruleId);
            $line = $issue->line ?? '-';

            $rows .= <<<HTML
                <tr class="severity-{$severityClass}" data-rule="{$ruleId}">
                    <td class="cell-severity">{$severityBadge}</td>
                    <td class="cell-file">{$file}</td>
                    <td class="cell-rule">{$ruleId}</td>
                    <td class="cell-column">{$column}</td>
                    <td class="cell-message">{$message}</td>
                    <td class="cell-line">{$line}</td>
                </tr>
HTML;
        }

        return <<<HTML
        <div class="issues-section">
            <h2>⚠️ Issues Found</h2>
            <div class="filters">
                <button class="filter-btn active" data-filter="all">All ({$this->calculateStats($issues)['total_issues']})</button>
                <button class="filter-btn" data-filter="error">Errors ({$this->calculateStats($issues)['errors']})</button>
                <button class="filter-btn" data-filter="warning">Warnings ({$this->calculateStats($issues)['warnings']})</button>
                <button class="filter-btn" data-filter="info">Info ({$this->calculateStats($issues)['info']})</button>
            </div>
            <div class="table-wrapper">
                <table class="issues-table">
                    <thead>
                        <tr>
                            <th>Severity</th>
                            <th>File</th>
                            <th>Rule</th>
                            <th>Column</th>
                            <th>Message</th>
                            <th>Line</th>
                        </tr>
                    </thead>
                    <tbody>
                        {$rows}
                    </tbody>
                </table>
            </div>
        </div>
HTML;
    }

    /**
     * Render grouped suggestions section.
     */
    protected function renderGroupedSuggestions(array $groupedIssues): string
    {
        $issuesWithSuggestions = array_filter($groupedIssues, function($issues) {
            return !empty($issues[0]->suggestion);
        });

        if (empty($issuesWithSuggestions)) {
            return '';
        }

        $suggestionsHtml = '';
        foreach ($issuesWithSuggestions as $ruleId => $issues) {
            $count = count($issues);
            $suggestion = nl2br(htmlspecialchars($issues[0]->suggestion));
            $docsUrl = $issues[0]->docsUrl ?? '';
            $docsLink = $docsUrl ? "<a href='{$docsUrl}' target='_blank' class='docs-link'>📖 Documentation</a>" : '';

            $suggestionsHtml .= <<<HTML
            <div class="suggestion-card">
                <div class="suggestion-header">
                    <h3>📋 {$ruleId}</h3>
                    <span class="occurrence-badge">{$count} occurrence(s)</span>
                </div>
                <div class="suggestion-content">
                    <pre>{$suggestion}</pre>
                </div>
                {$docsLink}
            </div>
HTML;
        }

        return <<<HTML
        <div class="suggestions-section">
            <h2>💡 Suggestions & Recommendations</h2>
            {$suggestionsHtml}
        </div>
HTML;
    }

    /**
     * Render rule breakdown section.
     */
    protected function renderRuleBreakdown(array $groupedIssues): string
    {
        $rows = '';
        foreach ($groupedIssues as $ruleId => $issues) {
            $count = count($issues);
            $errors = count(array_filter($issues, fn($i) => $i->severity === 'error'));
            $warnings = count(array_filter($issues, fn($i) => $i->severity === 'warning'));
            $info = count(array_filter($issues, fn($i) => $i->severity === 'info'));

            $rows .= <<<HTML
            <tr>
                <td><strong>{$ruleId}</strong></td>
                <td class="text-center">{$count}</td>
                <td class="text-center severity-error">{$errors}</td>
                <td class="text-center severity-warning">{$warnings}</td>
                <td class="text-center severity-info">{$info}</td>
            </tr>
HTML;
        }

        return <<<HTML
        <div class="breakdown-section">
            <h2>📈 Rule Breakdown</h2>
            <table class="breakdown-table">
                <thead>
                    <tr>
                        <th>Rule</th>
                        <th>Total</th>
                        <th>Errors</th>
                        <th>Warnings</th>
                        <th>Info</th>
                    </tr>
                </thead>
                <tbody>
                    {$rows}
                </tbody>
            </table>
        </div>
HTML;
    }

    /**
     * Get severity badge HTML.
     */
    protected function getSeverityBadge(string $severity): string
    {
        $icons = [
            'error' => '❌',
            'warning' => '⚠️',
            'info' => 'ℹ️',
        ];

        $icon = $icons[$severity] ?? '•';
        return "<span class='severity-badge severity-{$severity}'>{$icon} " . ucfirst($severity) . "</span>";
    }

    /**
     * Get CSS styles.
     */
    protected function getStyles(): string
    {
        return <<<CSS
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #f5f7fa;
            color: #2c3e50;
            line-height: 1.6;
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 2rem;
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 10px 25px rgba(102, 126, 234, 0.3);
        }

        .header h1 {
            font-size: 2rem;
            margin-bottom: 0.5rem;
        }

        .meta {
            display: flex;
            gap: 2rem;
            font-size: 0.9rem;
            opacity: 0.9;
        }

        .summary {
            background: white;
            padding: 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        .status-badge {
            display: flex;
            align-items: center;
            gap: 1rem;
            padding: 1rem;
            border-radius: 8px;
            margin-bottom: 1.5rem;
            font-size: 1.2rem;
            font-weight: 600;
        }

        .status-success { background: #d4edda; color: #155724; }
        .status-warning { background: #fff3cd; color: #856404; }
        .status-danger { background: #f8d7da; color: #721c24; }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 1rem;
        }

        .stat-card {
            background: #f8f9fa;
            padding: 1.5rem;
            border-radius: 8px;
            text-align: center;
            border-left: 4px solid #6c757d;
        }

        .stat-card.error { border-left-color: #dc3545; }
        .stat-card.warning { border-left-color: #ffc107; }
        .stat-card.info { border-left-color: #17a2b8; }

        .stat-value {
            font-size: 2.5rem;
            font-weight: bold;
            color: #2c3e50;
        }

        .stat-label {
            font-size: 0.9rem;
            color: #6c757d;
            margin-top: 0.5rem;
        }

        .chart-section, .issues-section, .suggestions-section, .breakdown-section {
            background: white;
            padding: 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        h2 {
            font-size: 1.5rem;
            margin-bottom: 1.5rem;
            color: #2c3e50;
        }

        .bar-chart {
            display: flex;
            height: 60px;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .bar-item {
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: 600;
            transition: opacity 0.3s;
        }

        .bar-item:hover { opacity: 0.8; }
        .bar-item.error { background: #dc3545; }
        .bar-item.warning { background: #ffc107; color: #333; }
        .bar-item.info { background: #17a2b8; }

        .filters {
            display: flex;
            gap: 0.5rem;
            margin-bottom: 1.5rem;
            flex-wrap: wrap;
        }

        .filter-btn {
            padding: 0.5rem 1rem;
            border: 2px solid #e0e0e0;
            background: white;
            border-radius: 6px;
            cursor: pointer;
            font-weight: 500;
            transition: all 0.3s;
        }

        .filter-btn:hover {
            border-color: #667eea;
            color: #667eea;
        }

        .filter-btn.active {
            background: #667eea;
            color: white;
            border-color: #667eea;
        }

        .table-wrapper {
            overflow-x: auto;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #f8f9fa;
            padding: 1rem;
            text-align: left;
            font-weight: 600;
            color: #495057;
            border-bottom: 2px solid #dee2e6;
        }

        td {
            padding: 1rem;
            border-bottom: 1px solid #e9ecef;
        }

        tbody tr:hover {
            background: #f8f9fa;
        }

        .severity-badge {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 4px;
            font-size: 0.85rem;
            font-weight: 600;
        }

        .severity-badge.severity-error {
            background: #dc3545;
            color: white;
        }

        .severity-badge.severity-warning {
            background: #ffc107;
            color: #333;
        }

        .severity-badge.severity-info {
            background: #17a2b8;
            color: white;
        }

        .text-center { text-align: center; }
        .severity-error { color: #dc3545; font-weight: 600; }
        .severity-warning { color: #ffc107; font-weight: 600; }
        .severity-info { color: #17a2b8; font-weight: 600; }

        .suggestion-card {
            background: #f8f9fa;
            padding: 1.5rem;
            border-radius: 8px;
            margin-bottom: 1.5rem;
            border-left: 4px solid #667eea;
        }

        .suggestion-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 1rem;
        }

        .suggestion-header h3 {
            font-size: 1.1rem;
            color: #2c3e50;
        }

        .occurrence-badge {
            background: #667eea;
            color: white;
            padding: 0.25rem 0.75rem;
            border-radius: 12px;
            font-size: 0.85rem;
        }

        .suggestion-content pre {
            background: white;
            padding: 1rem;
            border-radius: 6px;
            overflow-x: auto;
            font-size: 0.9rem;
            line-height: 1.6;
            border: 1px solid #e0e0e0;
        }

        .docs-link {
            display: inline-block;
            margin-top: 1rem;
            color: #667eea;
            text-decoration: none;
            font-weight: 500;
        }

        .docs-link:hover {
            text-decoration: underline;
        }

        .no-issues {
            text-align: center;
            padding: 3rem;
            font-size: 1.2rem;
            color: #28a745;
        }

        .footer {
            text-align: center;
            padding: 2rem;
            color: #6c757d;
            font-size: 0.9rem;
        }

        .footer a {
            color: #667eea;
            text-decoration: none;
        }

        .footer a:hover {
            text-decoration: underline;
        }

        @media (max-width: 768px) {
            .container {
                padding: 1rem;
            }

            .header h1 {
                font-size: 1.5rem;
            }

            .meta {
                flex-direction: column;
                gap: 0.5rem;
            }

            .stats-grid {
                grid-template-columns: repeat(2, 1fr);
            }

            .filters {
                flex-direction: column;
            }

            .filter-btn {
                width: 100%;
            }
        }
CSS;
    }

    /**
     * Get JavaScript code.
     */
    protected function getJavaScript(): string
    {
        return <<<JS
        // Filter functionality
        document.querySelectorAll('.filter-btn').forEach(btn => {
            btn.addEventListener('click', function() {
                // Update active button
                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
                this.classList.add('active');

                const filter = this.dataset.filter;
                const rows = document.querySelectorAll('.issues-table tbody tr');

                rows.forEach(row => {
                    if (filter === 'all') {
                        row.style.display = '';
                    } else {
                        row.style.display = row.classList.contains('severity-' + filter) ? '' : 'none';
                    }
                });
            });
        });

        // Add search functionality
        const searchHtml = '<div style="margin-bottom: 1rem;"><input type="text" id="searchInput" placeholder="Search issues..." style="width: 100%; padding: 0.75rem; border: 2px solid #e0e0e0; border-radius: 6px; font-size: 1rem;"></div>';
        document.querySelector('.filters').insertAdjacentHTML('afterend', searchHtml);

        document.getElementById('searchInput').addEventListener('input', function(e) {
            const searchTerm = e.target.value.toLowerCase();
            const rows = document.querySelectorAll('.issues-table tbody tr');

            rows.forEach(row => {
                const text = row.textContent.toLowerCase();
                row.style.display = text.includes(searchTerm) ? '' : 'none';
            });
        });
JS;
    }
}
