<?php

namespace Sufyan\MigrationLinter\Support;

class HtmlReporter
{
    /**
     * Generate HTML report from issues.
     *
     * @param  Issue[]  $issues
     * @param  string|null  $outputPath
     */
    public function generate(array $issues, ?string $outputPath = null): string
    {
        $html = $this->buildHtmlDocument($issues);

        if ($outputPath) {
            $directory = dirname($outputPath);
            if (! file_exists($directory)) {
                mkdir($directory, 0755, true);
            }

            file_put_contents($outputPath, $html);
        }

        return $html;
    }

    /**
     * Build complete HTML document.
     *
     * @param  Issue[]  $issues
     */
    protected function buildHtmlDocument(array $issues): string
    {
        $stats = $this->calculateStats($issues);
        $groupedIssues = $this->groupIssuesByRule($issues);
        $projectName = $this->escape(basename(getcwd()));
        $timestamp = date('Y-m-d H:i:s');

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laravel Migration Linter Report</title>
    <style>
{$this->getStyles()}
    </style>
</head>
<body>
    <div class="page-shell">
        <main class="container">
            <header class="header">
                <div class="header-top">
                    <h1>Laravel Migration Linter Report</h1>
                    <span class="status-pill {$this->getOverallStatusClass($stats)}">{$this->getOverallStatusText($stats)}</span>
                </div>
                <div class="meta-grid">
                    <div class="meta-item">
                        <span class="meta-label">Project</span>
                        <strong class="meta-value">{$projectName}</strong>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Generated</span>
                        <strong class="meta-value">{$timestamp}</strong>
                    </div>
                </div>
            </header>

            {$this->renderToolbar()}
            {$this->renderSummary($stats)}
            {$this->renderChart($stats)}
            {$this->renderIssuesTable($issues, $stats)}
            {$this->renderGroupedSuggestions($groupedIssues)}
            {$this->renderRuleBreakdown($groupedIssues)}

            <footer class="footer">
                <p>
                    Generated by
                    <a href="https://github.com/muhammad-sufyan5/sufyan-laravel-migration-lint-package" target="_blank" rel="noopener noreferrer">
                        Laravel Migration Linter
                    </a>
                </p>
            </footer>
        </main>
    </div>

    <script>
{$this->getJavaScript()}
    </script>
</body>
</html>
HTML;
    }

    /**
     * @param  Issue[]  $issues
     */
    protected function calculateStats(array $issues): array
    {
        $files = array_unique(array_map(fn ($issue) => $issue->file, $issues));

        return [
            'total_issues' => count($issues),
            'total_files' => count($files),
            'errors' => count(array_filter($issues, fn ($issue) => $issue->severity === 'error')),
            'warnings' => count(array_filter($issues, fn ($issue) => $issue->severity === 'warning')),
            'info' => count(array_filter($issues, fn ($issue) => $issue->severity === 'info')),
        ];
    }

    /**
     * @param  Issue[]  $issues
     */
    protected function groupIssuesByRule(array $issues): array
    {
        $grouped = [];

        foreach ($issues as $issue) {
            $grouped[$issue->ruleId][] = $issue;
        }

        return $grouped;
    }

    protected function renderToolbar(): string
    {
        return <<<HTML
            <section class="card report-toolbar">
                <div class="toolbar-left">
                    <strong>Report Controls</strong>
                    <span>Tailor this view for scanning, presentation, or printing.</span>
                </div>
                <div class="toolbar-actions">
                    <button type="button" id="toggleDensity" class="toolbar-btn">Compact Density</button>
                    <button type="button" id="toggleFocus" class="toolbar-btn">Focus Mode</button>
                    <button type="button" id="printReport" class="toolbar-btn">Print / Save PDF</button>
                </div>
            </section>
HTML;
    }

    protected function renderSummary(array $stats): string
    {
        $score = $this->calculateHealthScore($stats);
        $scoreClass = $score >= 85 ? 'is-strong' : ($score >= 65 ? 'is-moderate' : 'is-poor');

        return <<<HTML
            <section class="card summary-card">
                <div class="summary-headline">
                    <h2>Summary</h2>
                    <div class="quality-score {$scoreClass}">
                        <span class="score-label">Health Score</span>
                        <strong>{$score}</strong>
                    </div>
                </div>
                <div class="stats-grid">
                    <article class="stat-card">
                        <p class="stat-value">{$stats['total_issues']}</p>
                        <p class="stat-label">Total Issues</p>
                    </article>
                    <article class="stat-card">
                        <p class="stat-value">{$stats['total_files']}</p>
                        <p class="stat-label">Files Affected</p>
                    </article>
                    <article class="stat-card error">
                        <p class="stat-value">{$stats['errors']}</p>
                        <p class="stat-label">Errors</p>
                    </article>
                    <article class="stat-card warning">
                        <p class="stat-value">{$stats['warnings']}</p>
                        <p class="stat-label">Warnings</p>
                    </article>
                    <article class="stat-card info">
                        <p class="stat-value">{$stats['info']}</p>
                        <p class="stat-label">Info</p>
                    </article>
                </div>
                <p class="summary-note">Use this report to prioritize blocking risks first, then remove warning patterns before rollout.</p>
            </section>
HTML;
    }

    protected function renderChart(array $stats): string
    {
        $total = $stats['total_issues'];

        if ($total === 0) {
            return '';
        }

        $errorPercent = max(1, (int) round(($stats['errors'] / $total) * 100));
        $warningPercent = max(1, (int) round(($stats['warnings'] / $total) * 100));
        $infoPercent = max(1, (int) round(($stats['info'] / $total) * 100));

        return <<<HTML
            <section class="card chart-section">
                <h2>Issue Distribution</h2>
                <div class="bar-chart">
                    <div class="bar-item error" style="width: {$errorPercent}%">
                        <span class="bar-label">Errors {$stats['errors']}</span>
                    </div>
                    <div class="bar-item warning" style="width: {$warningPercent}%">
                        <span class="bar-label">Warnings {$stats['warnings']}</span>
                    </div>
                    <div class="bar-item info" style="width: {$infoPercent}%">
                        <span class="bar-label">Info {$stats['info']}</span>
                    </div>
                </div>
                <div class="chart-legend">
                    <span class="legend-item error-dot">Errors {$errorPercent}%</span>
                    <span class="legend-item warning-dot">Warnings {$warningPercent}%</span>
                    <span class="legend-item info-dot">Info {$infoPercent}%</span>
                </div>
            </section>
HTML;
    }

    /**
     * @param  Issue[]  $issues
     */
    protected function renderIssuesTable(array $issues, array $stats): string
    {
        if ($issues === []) {
            return '<section class="card"><div class="no-issues">No issues found. Your migrations look safe.</div></section>';
        }

        $rows = '';
        foreach ($issues as $issue) {
            $severity = $this->escape($issue->severity);
            $file = $this->escape(basename($issue->file));
            $ruleId = $this->escape($issue->ruleId);
            $column = $this->escape($issue->snippet ?? '-');
            $message = $this->escape($issue->message);
            $line = (int) ($issue->line ?? 0);
            $severityBadge = $this->getSeverityBadge($issue->severity);

            $rows .= <<<HTML
                <tr class="severity-{$severity}" data-severity="{$severity}" data-rule="{$ruleId}">
                    <td class="cell-severity">{$severityBadge}</td>
                    <td>{$file}</td>
                    <td><code>{$ruleId}</code></td>
                    <td><code>{$column}</code></td>
                    <td>{$message}</td>
                    <td>{$line}</td>
                </tr>
HTML;
        }

        return <<<HTML
            <section class="card issues-section">
                <div class="section-header">
                    <h2>Issues Found</h2>
                    <input type="text" id="searchInput" class="search-input" placeholder="Search by file, rule, message..." />
                </div>
                <div class="filters">
                    <button class="filter-btn active" data-filter="all">All ({$stats['total_issues']})</button>
                    <button class="filter-btn" data-filter="error">Errors ({$stats['errors']})</button>
                    <button class="filter-btn" data-filter="warning">Warnings ({$stats['warnings']})</button>
                    <button class="filter-btn" data-filter="info">Info ({$stats['info']})</button>
                </div>
                <div class="table-wrapper">
                    <table class="issues-table">
                        <thead>
                            <tr>
                                <th>Severity</th>
                                <th>File</th>
                                <th>Rule</th>
                                <th>Column</th>
                                <th>Message</th>
                                <th>Line</th>
                            </tr>
                        </thead>
                        <tbody>
{$rows}
                        </tbody>
                    </table>
                </div>
            </section>
HTML;
    }

    protected function renderGroupedSuggestions(array $groupedIssues): string
    {
        $issuesWithSuggestions = array_filter(
            $groupedIssues,
            fn (array $issues) => isset($issues[0]) && ! empty($issues[0]->suggestion)
        );

        if ($issuesWithSuggestions === []) {
            return '';
        }

        $cards = '';
        foreach ($issuesWithSuggestions as $ruleId => $issues) {
            $issueCount = count($issues);
            $safeRule = $this->escape((string) $ruleId);
            $safeSuggestion = nl2br($this->escape((string) $issues[0]->suggestion));
            $docsHtml = '';

            if (! empty($issues[0]->docsUrl)) {
                $safeUrl = $this->escape((string) $issues[0]->docsUrl);
                $docsHtml = "<a class=\"docs-link\" href=\"{$safeUrl}\" target=\"_blank\" rel=\"noopener noreferrer\">Open documentation</a>";
            }

            $cards .= <<<HTML
                <article class="suggestion-card">
                    <header class="suggestion-header">
                        <h3>{$safeRule}</h3>
                        <span class="occurrence-badge">{$issueCount} occurrence(s)</span>
                    </header>
                    <p class="suggestion-body">{$safeSuggestion}</p>
                    {$docsHtml}
                </article>
HTML;
        }

        return <<<HTML
            <section class="card suggestions-section">
                <h2>Suggestions & Recommendations</h2>
{$cards}
            </section>
HTML;
    }

    protected function renderRuleBreakdown(array $groupedIssues): string
    {
        if ($groupedIssues === []) {
            return '';
        }

        $rows = '';
        foreach ($groupedIssues as $ruleId => $issues) {
            $total = count($issues);
            $errors = count(array_filter($issues, fn ($issue) => $issue->severity === 'error'));
            $warnings = count(array_filter($issues, fn ($issue) => $issue->severity === 'warning'));
            $info = count(array_filter($issues, fn ($issue) => $issue->severity === 'info'));

            $safeRule = $this->escape((string) $ruleId);

            $rows .= <<<HTML
                <tr>
                    <td><code>{$safeRule}</code></td>
                    <td>{$total}</td>
                    <td class="severity-error">{$errors}</td>
                    <td class="severity-warning">{$warnings}</td>
                    <td class="severity-info">{$info}</td>
                </tr>
HTML;
        }

        return <<<HTML
            <section class="card breakdown-section">
                <h2>Rule Breakdown</h2>
                <div class="table-wrapper">
                    <table class="breakdown-table">
                        <thead>
                            <tr>
                                <th>Rule</th>
                                <th>Total</th>
                                <th>Errors</th>
                                <th>Warnings</th>
                                <th>Info</th>
                            </tr>
                        </thead>
                        <tbody>
{$rows}
                        </tbody>
                    </table>
                </div>
            </section>
HTML;
    }

    protected function getSeverityBadge(string $severity): string
    {
        $safeSeverity = $this->escape($severity);

        return "<span class=\"severity-badge severity-{$safeSeverity}\">".ucfirst($safeSeverity).'</span>';
    }

    protected function getOverallStatusClass(array $stats): string
    {
        if ($stats['errors'] > 0) {
            return 'is-danger';
        }

        if ($stats['warnings'] > 0) {
            return 'is-warning';
        }

        return 'is-success';
    }

    protected function getOverallStatusText(array $stats): string
    {
        if ($stats['errors'] > 0) {
            return 'Action required';
        }

        if ($stats['warnings'] > 0) {
            return 'Review recommended';
        }

        return 'All clear';
    }

    protected function calculateHealthScore(array $stats): int
    {
        if ($stats['total_issues'] === 0) {
            return 100;
        }

        $weightedRisk = ($stats['errors'] * 10) + ($stats['warnings'] * 4) + ($stats['info'] * 1.5);
        $penalty = min(100, (int) round(($weightedRisk / max(1, $stats['total_issues'])) * 4));

        return max(0, 100 - $penalty);
    }

    protected function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
    }

    protected function getStyles(): string
    {
        return <<<CSS
* {
    box-sizing: border-box;
}

:root {
    --bg: #f3f6fb;
    --card: #ffffff;
    --text: #122033;
    --muted: #5e6d80;
    --line: #d7dfeb;
    --brand: #0a5eb0;
    --brand-dark: #084a8a;
    --success: #1f8f54;
    --warning: #c4821f;
    --danger: #c73535;
    --info: #2379a8;
    --shadow: 0 14px 38px rgba(16, 41, 77, 0.09);
}

body {
    margin: 0;
    font-family: "Aptos", "Trebuchet MS", "Segoe UI", Tahoma, sans-serif;
    color: var(--text);
    background:
        radial-gradient(circle at 10% 5%, rgba(10, 94, 176, 0.08), transparent 30%),
        radial-gradient(circle at 85% 0%, rgba(31, 143, 84, 0.08), transparent 34%),
        var(--bg);
}

.page-shell {
    min-height: 100vh;
    padding: 32px 16px;
}

.container {
    width: min(1180px, 100%);
    margin: 0 auto;
}

.header {
    background: linear-gradient(135deg, #0a5eb0, #0f3f73);
    color: #ffffff;
    border-radius: 16px;
    box-shadow: var(--shadow);
    padding: 24px;
    margin-bottom: 20px;
}

.header h1 {
    margin: 0;
    font-size: 30px;
    letter-spacing: 0.2px;
}

.header-top {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 12px;
    margin-bottom: 16px;
}

.status-pill {
    border-radius: 999px;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.7px;
    padding: 8px 12px;
    background: rgba(255, 255, 255, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.35);
}

.status-pill.is-danger {
    background: rgba(199, 53, 53, 0.2);
}

.status-pill.is-warning {
    background: rgba(196, 130, 31, 0.22);
}

.status-pill.is-success {
    background: rgba(31, 143, 84, 0.25);
}

.meta-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 16px;
}

.meta-item {
    border: 1px solid rgba(255, 255, 255, 0.24);
    border-radius: 10px;
    padding: 12px;
    background: rgba(255, 255, 255, 0.08);
}

.meta-label {
    display: block;
    font-size: 12px;
    opacity: 0.84;
    margin-bottom: 4px;
}

.meta-value {
    font-size: 14px;
}

.card {
    background: var(--card);
    border-radius: 14px;
    box-shadow: var(--shadow);
    border: 1px solid #edf2fa;
    padding: 20px;
    margin-bottom: 16px;
}

h2 {
    margin: 0 0 14px 0;
    font-size: 20px;
}

.report-toolbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 14px;
    margin-bottom: 14px;
}

.toolbar-left strong {
    display: block;
    font-size: 15px;
}

.toolbar-left span {
    font-size: 13px;
    color: var(--muted);
}

.toolbar-actions {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
}

.toolbar-btn {
    border: 1px solid var(--line);
    border-radius: 999px;
    background: #ffffff;
    color: #1f2c3d;
    padding: 8px 12px;
    cursor: pointer;
    font-size: 12px;
    font-weight: 600;
}

.toolbar-btn:hover {
    border-color: var(--brand);
    color: var(--brand-dark);
}

.summary-headline {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    margin-bottom: 14px;
}

.quality-score {
    border-radius: 12px;
    padding: 8px 12px;
    border: 1px solid var(--line);
    display: flex;
    align-items: baseline;
    gap: 8px;
}

.score-label {
    font-size: 12px;
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.3px;
}

.quality-score strong {
    font-size: 22px;
}

.quality-score.is-strong {
    border-color: rgba(31, 143, 84, 0.35);
    background: rgba(31, 143, 84, 0.08);
}

.quality-score.is-moderate {
    border-color: rgba(196, 130, 31, 0.35);
    background: rgba(196, 130, 31, 0.08);
}

.quality-score.is-poor {
    border-color: rgba(199, 53, 53, 0.35);
    background: rgba(199, 53, 53, 0.08);
}

.stats-grid {
    display: grid;
    grid-template-columns: repeat(5, minmax(0, 1fr));
    gap: 12px;
}

.stat-card {
    border: 1px solid var(--line);
    border-radius: 12px;
    padding: 14px;
    background: #f8fbff;
}

.stat-card.error {
    border-color: rgba(199, 53, 53, 0.35);
}

.stat-card.warning {
    border-color: rgba(196, 130, 31, 0.35);
}

.stat-card.info {
    border-color: rgba(35, 121, 168, 0.35);
}

.stat-value {
    margin: 0;
    font-size: 26px;
    font-weight: 700;
}

.stat-label {
    margin: 6px 0 0;
    color: var(--muted);
    font-size: 13px;
}

.summary-note {
    margin: 14px 0 0;
    padding: 10px 12px;
    border-radius: 10px;
    background: #f7fbff;
    border: 1px solid #dce9f8;
    color: #2b3e57;
    font-size: 13px;
}

.bar-chart {
    display: flex;
    min-height: 42px;
    border-radius: 10px;
    overflow: hidden;
    border: 1px solid var(--line);
}

.bar-item {
    display: flex;
    align-items: center;
    justify-content: center;
    min-width: 42px;
    font-size: 12px;
    font-weight: 600;
    color: #ffffff;
}

.bar-item.warning {
    color: #1f2630;
}

.bar-item.error {
    background: var(--danger);
}

.bar-item.warning {
    background: #efb450;
}

.bar-item.info {
    background: var(--info);
}

.chart-legend {
    display: flex;
    gap: 14px;
    flex-wrap: wrap;
    margin-top: 10px;
}

.legend-item {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    color: #2b3e57;
}

.legend-item::before {
    content: "";
    width: 9px;
    height: 9px;
    border-radius: 50%;
}

.legend-item.error-dot::before {
    background: var(--danger);
}

.legend-item.warning-dot::before {
    background: #efb450;
}

.legend-item.info-dot::before {
    background: var(--info);
}

.section-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    margin-bottom: 12px;
}

.search-input {
    width: min(360px, 100%);
    border: 1px solid var(--line);
    border-radius: 10px;
    padding: 10px 12px;
    font-size: 14px;
}

.search-input:focus {
    border-color: var(--brand);
    outline: 2px solid rgba(10, 94, 176, 0.18);
}

.filters {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    margin-bottom: 12px;
}

.filter-btn {
    border: 1px solid var(--line);
    border-radius: 999px;
    background: #ffffff;
    color: #1f2c3d;
    padding: 8px 12px;
    cursor: pointer;
    font-size: 13px;
}

.filter-btn:hover {
    border-color: var(--brand);
    color: var(--brand-dark);
}

.filter-btn.active {
    background: var(--brand);
    border-color: var(--brand);
    color: #ffffff;
}

.table-wrapper {
    overflow-x: auto;
    border: 1px solid var(--line);
    border-radius: 12px;
}

table {
    width: 100%;
    border-collapse: collapse;
    min-width: 780px;
}

th,
td {
    border-bottom: 1px solid var(--line);
    padding: 11px 12px;
    font-size: 13px;
    text-align: left;
    vertical-align: top;
}

th {
    background: #f5f8fd;
    font-size: 12px;
    letter-spacing: 0.3px;
    text-transform: uppercase;
    color: #2b3e57;
}

.issues-table tbody tr:hover,
.breakdown-table tbody tr:hover {
    background: #f7fbff;
}

.issues-table thead th {
    position: sticky;
    top: 0;
    z-index: 2;
}

.issues-table tbody tr.hidden {
    display: none;
}

.severity-badge {
    border-radius: 999px;
    display: inline-flex;
    font-weight: 700;
    font-size: 11px;
    letter-spacing: 0.2px;
    padding: 4px 9px;
    text-transform: uppercase;
}

.severity-badge.severity-error {
    color: #ffffff;
    background: var(--danger);
}

.severity-badge.severity-warning {
    color: #1f2630;
    background: #efb450;
}

.severity-badge.severity-info {
    color: #ffffff;
    background: var(--info);
}

.severity-error {
    color: var(--danger);
    font-weight: 700;
}

.severity-warning {
    color: var(--warning);
    font-weight: 700;
}

.severity-info {
    color: var(--info);
    font-weight: 700;
}

.suggestion-card {
    border: 1px solid var(--line);
    border-left: 4px solid var(--brand);
    border-radius: 12px;
    padding: 14px;
    background: #fbfdff;
    margin-bottom: 10px;
}

.suggestion-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 8px;
    margin-bottom: 8px;
}

.suggestion-header h3 {
    margin: 0;
}

.occurrence-badge {
    background: rgba(10, 94, 176, 0.12);
    color: var(--brand-dark);
    border: 1px solid rgba(10, 94, 176, 0.24);
    border-radius: 999px;
    font-size: 12px;
    font-weight: 700;
    padding: 4px 10px;
}

.suggestion-body {
    margin: 0;
    line-height: 1.55;
    color: #2c3d52;
}

.docs-link {
    display: inline-block;
    margin-top: 8px;
    color: var(--brand);
    text-decoration: none;
    font-weight: 600;
    font-size: 13px;
}

.docs-link:hover {
    text-decoration: underline;
}

.no-issues {
    border: 1px solid rgba(31, 143, 84, 0.26);
    background: rgba(31, 143, 84, 0.08);
    color: #175437;
    border-radius: 10px;
    padding: 18px;
    text-align: center;
    font-weight: 600;
}

code {
    font-family: Consolas, "Courier New", monospace;
    font-size: 12px;
    padding: 1px 4px;
    border-radius: 4px;
    background: #eef4fb;
    color: #274160;
}

.footer {
    color: var(--muted);
    text-align: center;
    padding: 10px;
    font-size: 13px;
}

.footer a {
    color: var(--brand);
}

.is-compact td,
.is-compact th {
    padding: 8px 9px;
    font-size: 12px;
}

.is-compact .card {
    padding: 14px;
}

.is-focus .report-toolbar,
.is-focus .suggestions-section,
.is-focus .breakdown-section {
    display: none;
}

@media print {
    body {
        background: #ffffff;
    }

    .page-shell {
        padding: 0;
    }

    .card,
    .header {
        box-shadow: none;
        border: 1px solid #d0d8e3;
        break-inside: avoid;
    }

    .report-toolbar,
    .search-input,
    .filters,
    .footer {
        display: none;
    }
}

@media (max-width: 768px) {
    .page-shell {
        padding: 12px;
    }

    .header {
        padding: 18px;
    }

    .header h1 {
        font-size: 23px;
    }

    .header-top {
        flex-direction: column;
        align-items: flex-start;
    }

    .report-toolbar,
    .summary-headline {
        flex-direction: column;
        align-items: flex-start;
    }

    .meta-grid {
        grid-template-columns: 1fr;
    }

    .stats-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
    }

    .section-header {
        flex-direction: column;
        align-items: stretch;
    }

    .filters {
        flex-direction: column;
    }

    .filter-btn {
        width: 100%;
        text-align: left;
    }
}
CSS;
    }

    protected function getJavaScript(): string
    {
        return <<<JS
const rows = Array.from(document.querySelectorAll('.issues-table tbody tr'));
const filterButtons = Array.from(document.querySelectorAll('.filter-btn'));
const searchInput = document.getElementById('searchInput');
const densityButton = document.getElementById('toggleDensity');
const focusButton = document.getElementById('toggleFocus');
const printButton = document.getElementById('printReport');

function applyFilters() {
    if (!rows.length) {
        return;
    }

    const activeButton = document.querySelector('.filter-btn.active');
    const activeFilter = activeButton ? activeButton.dataset.filter : 'all';
    const query = searchInput ? searchInput.value.trim().toLowerCase() : '';

    rows.forEach((row) => {
        const rowSeverity = row.dataset.severity;
        const severityMatch = activeFilter === 'all' || rowSeverity === activeFilter;
        const textMatch = query === '' || row.textContent.toLowerCase().includes(query);
        row.classList.toggle('hidden', !(severityMatch && textMatch));
    });
}

filterButtons.forEach((button) => {
    button.addEventListener('click', () => {
        filterButtons.forEach((item) => item.classList.remove('active'));
        button.classList.add('active');
        applyFilters();
    });
});

if (searchInput) {
    searchInput.addEventListener('input', applyFilters);
}

if (densityButton) {
    densityButton.addEventListener('click', () => {
        document.body.classList.toggle('is-compact');
        densityButton.textContent = document.body.classList.contains('is-compact')
            ? 'Comfortable Density'
            : 'Compact Density';
    });
}

if (focusButton) {
    focusButton.addEventListener('click', () => {
        document.body.classList.toggle('is-focus');
        focusButton.textContent = document.body.classList.contains('is-focus')
            ? 'Show Full Report'
            : 'Focus Mode';
    });
}

if (printButton) {
    printButton.addEventListener('click', () => {
        window.print();
    });
}

applyFilters();
JS;
    }
}
